package com.maycon.hotelaria.gui;

import com.maycon.hotelaria.estruturas.Quarto;
import com.maycon.hotelaria.dao.QuartoDAO;
import com.maycon.hotelaria.tabelas.TabelaFactory;
import javax.swing.JOptionPane;
import static com.maycon.hotelaria.validacoes.Validacoes.validaNumQuarto; //MANEIRA DE CHAMAR UM MÉTODO ESTÁTICO PARA EXECUÇÃO
import java.util.List;

public class CadastroQuartos extends javax.swing.JFrame {

    public CadastroQuartos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbTipoQuarto = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        ftxtValorDiaria = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuartos = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaInformacoes = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        txtNumQuarto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Hotelaria");
        setMinimumSize(new java.awt.Dimension(800, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Consulta de Quartos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Número do quarto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Escolha o tipo do quarto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 180, -1));

        cbTipoQuarto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um tipo de quarto", "Solteiro", "Duplo", "Triplo", "Casal" }));
        cbTipoQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(cbTipoQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 210, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Valor da diária:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, -1, -1));

        ftxtValorDiaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        getContentPane().add(ftxtValorDiaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 80, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Informações adicionais:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 103, 35));

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 103, 35));

        tbQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número do Quarto", "Tipo", "Diária", "Informações"
            }
        ){
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        }
    );
    tbQuartos.setRowSelectionAllowed(false);
    jScrollPane1.setViewportView(tbQuartos);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 840, 120));

    btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btnConsultar.setText("Consultar");
    btnConsultar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnConsultarActionPerformed(evt);
        }
    });
    getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 103, 35));

    jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    jLabel7.setText("Cadastro de Quartos");
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, -1));

    txaInformacoes.setColumns(20);
    txaInformacoes.setRows(5);
    jScrollPane2.setViewportView(txaInformacoes);

    getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 650, 100));

    jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jButton1.setText("Voltar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 423, 120, 40));
    getContentPane().add(txtNumQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 80, -1));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoQuartoActionPerformed

    }//GEN-LAST:event_cbTipoQuartoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNumQuarto.setText("");
        txaInformacoes.setText("");
        cbTipoQuarto.setSelectedItem(0);
        ftxtValorDiaria.setText("");
        cbTipoQuarto.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        //PROGRAMAÇÃO DEFENSIVA       
        if (txtNumQuarto.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite o número do quarto!", "Campo Vazio!", JOptionPane.WARNING_MESSAGE);
            txtNumQuarto.requestFocus();
            return;
        }

        if (!(validaNumQuarto(txtNumQuarto.getText()))) {
            JOptionPane.showMessageDialog(rootPane, "Digite número do quarto válido!", "Erro no campo!", JOptionPane.WARNING_MESSAGE);
            txtNumQuarto.setText("");
            txtNumQuarto.requestFocus();
            return;
        }

        if (ftxtValorDiaria.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite o valor da diária!", "Campo Vazio!", JOptionPane.WARNING_MESSAGE);
            ftxtValorDiaria.requestFocus();
            return;
        }

        if (cbTipoQuarto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um tipo de quarto!", "Erro!", JOptionPane.WARNING_MESSAGE);
            cbTipoQuarto.requestFocus();
            return;
        }

        Quarto quarto = new Quarto();
        QuartoDAO quartoDAO = new QuartoDAO();
        quarto.setNumQuarto(Integer.parseInt(txtNumQuarto.getText()));
        quarto.setTipoQuarto(cbTipoQuarto.getSelectedItem().toString());
        quarto.setValorDiaria(Double.parseDouble(ftxtValorDiaria.getText().replace(".", "").replace(",", ".")));
        quarto.setInformacoes(txaInformacoes.getText());

        if (quartoDAO.cadastraQuarto(quarto)) {
            JOptionPane.showMessageDialog(rootPane, "Quarto cadastrado com sucesso!", "Cadastro!", JOptionPane.INFORMATION_MESSAGE);

            Object cabecalho[] = {"Número do Quarto", "Tipo do Quarto", "Valor da Diária", "Informações"};
            List<Quarto> quartos = new QuartoDAO().consultaTodosQuartos();

            Object[][] dadosTable = new Object[quartos.size()][4];

            for (int i = 0; i < quartos.size(); i++) {
                Quarto quartoTmp = quartos.get(i);
                dadosTable[i] = new Object[]{quartoTmp.getNumQuarto(), quartoTmp.getTipoQuarto(), quartoTmp.getValorDiaria(), quartoTmp.getInformacoes()};
            }

            TabelaFactory.createTable(cabecalho, dadosTable, tbQuartos);
            txtNumQuarto.setText("");
            cbTipoQuarto.setSelectedIndex(0);
            ftxtValorDiaria.setText("");
            txaInformacoes.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Problema no cadastro do quarto!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Object cabecalho[] = {"Número do Quarto", "Tipo do Quarto", "Valor da Diária", "Informações"};
        List<Quarto> quartos = new QuartoDAO().consultaTodosQuartos();

        Object[][] dadosTable = new Object[quartos.size()][4];

        for (int i = 0; i < quartos.size(); i++) {
            Quarto quartoTmp = quartos.get(i);
            dadosTable[i] = new Object[]{quartoTmp.getNumQuarto(), quartoTmp.getTipoQuarto(), quartoTmp.getValorDiaria(), quartoTmp.getInformacoes()};
        }
        TabelaFactory.createTable(cabecalho, dadosTable, tbQuartos);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new MenuAdmin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox cbTipoQuarto;
    private javax.swing.JFormattedTextField ftxtValorDiaria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbQuartos;
    private javax.swing.JTextArea txaInformacoes;
    private javax.swing.JTextField txtNumQuarto;
    // End of variables declaration//GEN-END:variables
}
