package com.maycon.hotelaria.gui;

import com.maycon.hotelaria.estruturas.Quarto;
import com.maycon.hotelaria.dao.QuartoDAO;
import com.maycon.hotelaria.tabelas.TabelaFactory;
import javax.swing.JOptionPane;
import static com.maycon.hotelaria.validacoes.Validacoes.validaNumQuarto; //MANEIRA DE CHAMAR UM MÃ‰TODO ESTÃ?TICO PARA EXECUÃ‡ÃƒO
import java.util.List;

public class CadastroQuartos extends javax.swing.JFrame {

    public CadastroQuartos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbTipoQuarto = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        ftxtValorDiaria = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuartos = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaInformacoes = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        txtNumQuarto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Hotelaria");
        setMinimumSize(new java.awt.Dimension(800, 510));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Consulta de Quartos");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Número do quarto:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Escolha o tipo do quarto:");

        cbTipoQuarto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um tipo de quarto", "Solteiro", "Duplo", "Triplo", "Casal" }));
        cbTipoQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoQuartoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Valor da diária:");

        ftxtValorDiaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Informações adicionais:");

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tbQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número do Quarto", "Tipo", "Diária", "Informações"
            }
        ){
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        }
    );
    tbQuartos.setRowSelectionAllowed(false);
    jScrollPane1.setViewportView(tbQuartos);

    btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btnConsultar.setText("Consultar");
    btnConsultar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnConsultarActionPerformed(evt);
        }
    });

    jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    jLabel7.setText("Cadastro de Quartos");

    txaInformacoes.setColumns(20);
    txaInformacoes.setRows(5);
    jScrollPane2.setViewportView(txaInformacoes);

    jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jButton1.setText("Voltar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel7))
        .addGroup(layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel2)
            .addGap(9, 9, 9)
            .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(cbTipoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(jLabel5)
            .addGap(6, 6, 6)
            .addComponent(ftxtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel3)
            .addGap(4, 4, 4)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createSequentialGroup()
            .addGap(310, 310, 310)
            .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(37, 37, 37)
            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(layout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(jLabel7)
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jLabel2))
                .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4)
                .addComponent(cbTipoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addComponent(ftxtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel3))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(15, 15, 15)
            .addComponent(jLabel1)
            .addGap(11, 11, 11)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(13, 13, 13)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoQuartoActionPerformed

    }//GEN-LAST:event_cbTipoQuartoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNumQuarto.setText("");
        txaInformacoes.setText("");
        cbTipoQuarto.setSelectedItem(0);
        ftxtValorDiaria.setText("");
        cbTipoQuarto.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        //PROGRAMAÃ‡ÃƒO DEFENSIVA       
        if (txtNumQuarto.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite o nÃºmero do quarto!", "Campo Vazio!", JOptionPane.WARNING_MESSAGE);
            txtNumQuarto.requestFocus();
            return;
        }

        if (!(validaNumQuarto(txtNumQuarto.getText()))) {
            JOptionPane.showMessageDialog(rootPane, "Digite nÃºmero do quarto vÃ¡lido!", "Erro no campo!", JOptionPane.WARNING_MESSAGE);
            txtNumQuarto.setText("");
            txtNumQuarto.requestFocus();
            return;
        }

        if (ftxtValorDiaria.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite o valor da diÃ¡ria!", "Campo Vazio!", JOptionPane.WARNING_MESSAGE);
            ftxtValorDiaria.requestFocus();
            return;
        }

        if (cbTipoQuarto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um tipo de quarto!", "Erro!", JOptionPane.WARNING_MESSAGE);
            cbTipoQuarto.requestFocus();
            return;
        }

        Quarto quarto = new Quarto();
        QuartoDAO quartoDAO = new QuartoDAO();
        quarto.setNumQuarto(Integer.parseInt(txtNumQuarto.getText()));
        quarto.setTipoQuarto(cbTipoQuarto.getSelectedItem().toString());
        quarto.setValorDiaria(Double.parseDouble(ftxtValorDiaria.getText().replace(".", "").replace(",", ".")));
        quarto.setInformacoes(txaInformacoes.getText());

        if (quartoDAO.cadastraQuarto(quarto)) {
            JOptionPane.showMessageDialog(rootPane, "Quarto cadastrado com sucesso!", "Cadastro!", JOptionPane.INFORMATION_MESSAGE);

            Object cabecalho[] = {"NÃºmero do Quarto", "Tipo do Quarto", "Valor da DiÃ¡ria", "InformaÃ§Ãµes"};
            List<Quarto> quartos = new QuartoDAO().consultaTodosQuartos();

            Object[][] dadosTable = new Object[quartos.size()][4];

            for (int i = 0; i < quartos.size(); i++) {
                Quarto quartoTmp = quartos.get(i);
                dadosTable[i] = new Object[]{quartoTmp.getNumQuarto(), quartoTmp.getTipoQuarto(), quartoTmp.getValorDiaria(), quartoTmp.getInformacoes()};
            }

            TabelaFactory.createTable(cabecalho, dadosTable, tbQuartos);
            txtNumQuarto.setText("");
            cbTipoQuarto.setSelectedIndex(0);
            ftxtValorDiaria.setText("");
            txaInformacoes.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Problema no cadastro do quarto!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Object cabecalho[] = {"Numero do Quarto", "Tipo do Quarto", "Valor da Diaria", "Informaçoes"};
        List<Quarto> quartos = new QuartoDAO().consultaTodosQuartos();

        Object[][] dadosTable = new Object[quartos.size()][4];

        for (int i = 0; i < quartos.size(); i++) {
            Quarto quartoTmp = quartos.get(i);
            dadosTable[i] = new Object[]{quartoTmp.getNumQuarto(), quartoTmp.getTipoQuarto(), quartoTmp.getValorDiaria(), quartoTmp.getInformacoes()};
        }
        TabelaFactory.createTable(cabecalho, dadosTable, tbQuartos);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new MenuAdmin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox cbTipoQuarto;
    private javax.swing.JFormattedTextField ftxtValorDiaria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbQuartos;
    private javax.swing.JTextArea txaInformacoes;
    private javax.swing.JTextField txtNumQuarto;
    // End of variables declaration//GEN-END:variables
}
